### ISSUE TITLE
boot_finished.save file is empty

### ISSUE THREAD

**Issue by pera1998** [aesuli/Kindle-Photo-Frame#1]
Hi Andrea,

first of all thanks for the Photo Frame. Thanks to your guide i could install it. I just have one small problem. When I want to enable the autostart i get stuck on the step with modifying the boot_finished.save file. 

My file is empty.

Do you know what I can do in this case? What should paste into it?

I tried it on an Kindle Touch 4 (Model Nr. D01200)

**Comment by aesuli** [comment]
Hi, I'm happy you like it.
It is not clear to me why you use the '.save' extension. The file on my device is 'boot_finished' with no extension. Maybe on your device the names are different?
I do not have the device you have, so I cannot give you a safe advice on this (safe as avoiding to tell you "try this" and then your device is bricked).
Maybe you may look for help on the mobileread forum, which is a incredible resource of knowledge and talented people.
I've found most of the information I needed to build photoframe on mobileread.

**Comment by pera1998** [comment]
Hi, thanks for the reply. Thanks for the suggestion, i will have a look at the mobileread forum

**Comment by aesuli** [comment]
I'm closing the issue as "not planned". Whenever you'll find a solution you are very welcome to reopen it and add your information.
